default:
  image: php:7.3
  before_script:
    - apt-get update -yqq
    - apt-get install git zip zlib1g-dev libzip-dev libxml2-dev libpng-dev libghc-curl-dev libldb-dev libldap2-dev -yqq
    - docker-php-ext-install zip xml intl mbstring gd curl bcmath opcache
    - pecl install xdebug \
      && docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php

stages:
  - tests

# Tests PHPUNIT
test:phpunit:
  inherit:
    default: true
  stage: tests
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - cp phpunit.xml.dist phpunit.xml
    - php composer.phar install
    - sed -i -e 's/%%CLIENT_ID%%/${ENEDIS_CLIENT_ID}/g' phpunit.xml
    - sed -i -e 's/%%CLIENT_SECRET%%/${ENEDIS_CLIENT_SECRET}/g' phpunit.xml
    - php vendor/bin/phpunit --coverage-text --colors=never
